apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: spring-petclinic
    repoURL: https://rawlingsj.github.io/spring-petclinic
    targetRevision: "10"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true